### ISSUE TITLE
`sed` failure

### ISSUE THREAD

**Issue by Fmstrat** [Kayuii/hpool-miner#4]
This no longer works (from README):
```
version: "3"

services:
  miner:
    image: kayuii/hpool-miner:v1.4.1-1
    restart: always
    volumes:
      - /mnt/dst:/mnt/dst
      - /opt/chia/logs:/opt/log
      - /opt/chia/config.yaml:/opt/config.yaml
    command:
      - hpool-chia-miner
```

The new `sed -i` fails since config.yaml is mounted outside, it can't "mv/replace" since it can't skirt the filesystem. With `set -x` in the `entrypoint.sh`:
```
+ echo hpool-chia-miner
+ cut -c1
+ [ h = - ]
+ [ hpool-chia-miner = hpool-chia-miner ]
+ [ -n  ]
+ sed -i /path:$/c path: [ '/mnt/dst' ] config.yaml
sed: cannot rename ./sedq0HrNY: Device or resource busy
```
