### ISSUE TITLE
How to start xproxy in docker ?

### ISSUE THREAD

**Issue by error105** [Kayuii/hpool-miner#7]
How can i start the xproxy on this docker same time with chia-miner ?

**Comment by Kayuii** [comment]
```
version: "3"
services:
  xproxy:
    image: kayuii/hpool-miner:xproxy-og-v1.6.0
    restart: unless-stopped
    ports: [ "9190:9190" ]
    command:
      - x-proxy
    volumes:
      - /home/chia/xproxy/db:/opt/db/
      - /home/chia/xproxy/log:/opt/log
```
