### ISSUE TITLE
我如何掛載本地端含有plot的硬碟到docker內呢？

### ISSUE THREAD

**Issue by kihcl** [Kayuii/hpool-miner#9]
你好

我不會設定本地端硬碟掛載到docker內的hpool miner

config.yaml設定文件內的path該如何填寫呢？

**Comment by Kayuii** [comment]
```
version: "3"

services:
  miner:
    image: kayuii/hpool-miner:v1.5.0-7
    restart: always
    volumes:
      - /mnt/dst:/mnt/dst
      - /opt/chia/logs:/opt/log
    environment:
      - DIR=["/mnt/dst"]
      - APIKEY=1df8e525-772f-40e9-908d-0f26e36f8046
      - HOSTNAME=miner
      - LOGPATH=./logs/
      - SCAN=30
      - LANG=cn
      - PROXY=http://192.168.1.88:9190
      - MTLOAD=true
    command:
      - hpool-chia-miner
 ```

```
volumes:
      - /mnt/dst:/mnt/dst
      - local/patch/for/you/disk:patch/for/docker

environment:
      - DIR=["/mnt/dst","patch/for/docker"]
```
